### ISSUE TITLE
Qual o tipo de estatísitca deste DB?

### ISSUE THREAD

**Issue by henriqueal** [GabrielTF141/cartola-stats#2]
Fala Gabriel.

Blz?

Estava navegando pelo git do wgneial e achei vc em um comentários. Gostaria de saber quais as informações você armazena neste DB. Além disso, gostaria de saber se você possui informações do mercado em cada rodada.

**Comment by GabrielRato** [comment]
Eae cara, blz.
Eu cheguei a rodar algumas querys, usando média de gols, defesas mais vazadas etc, isso não está explicitamente armazenado em nenhuma tabela, mas pode ser obtido dando alguns merge etc.
Sim, tem informações de cada rodada, respectivo a cada jogador, fica na tabela "scout" acho q eu parei de rodar o script na rodada 16, mas se tu der uma lida no código tu pode ir rodando pra rodadas de hoje em diante, a API do cartola infelizmente não permite vc acessar os scouts de rodas anteriores...
